server:
  port: 8086
spring:
  rabbitmq:
    host: 47.108.69.93
    username: admin
    password: admin
    virtual-host: /donggua
  application:
    name: sms-service
  redis:
    host: 47.108.69.93
#用于可变参数传递
dg:
  sms:
    accessKeyId: LTAI4arl2Kfy234Q
    accessKeySecret: ghziLep8123447TF9R3zxrmBk43TPg
    signName: 冬瓜商城 #签名名称
    verifyCodeTemplate: SMS_172970120 #模板编号